class TOC {
	#include "ADEP\ABDEP\toc.sqe"
};
class MOB {
	#include "ADEP\ABDEP\mob.sqe"
};
class FOB {
	#include "ADEP\ABDEP\fob.sqe"
};
class COP {
	#include "ADEP\ABDEP\cop.sqe"
};
class FCP {
	#include "ADEP\ABDEP\fcp.sqe"
};
class FSP {
	#include "ADEP\ABDEP\fsp.sqe"
};
class PB {
	#include "ADEP\ABDEP\pb.sqe"
};
class RH {
	#include "ADEP\ABDEP\rh.sqe"
};
class HFP {
	#include "ADEP\ABDEP\hfp.sqe"
};
class HFPR {
	#include "ADEP\ABDEP\hfpr.sqe"
};	
class PFP {
	#include "ADEP\ABDEP\pfp.sqe"
};
